apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mascotas
  name: mascotas
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mascotas
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: mascotas
    spec:
      containers:
        - args:
            - sh
            - -c
            - /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_NAME
              value: mascotasdb
            - name: DB_PASSWORD
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: JAEGER_AGENT_HOST
              value: jaegertracingio
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
            - name: JAEGER_SAMPLER_TYPE
              value: const
          image: elgat02/demo64-mascotas
          name: mascotas
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
